#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: kafka Status
  hosts: FND-KFK
  max_fail_percentage: 0
  become: yes
  tags: [kafka]
  tasks:
    - { include: roles/monasca-variables/tasks/service_status.yml, service_name: kafka}

- name: influxdb Status
  hosts: FND-IDB
  max_fail_percentage: 0
  become: yes
  tags: [influxdb]
  vars_files:
    - roles/monasca-variables/vars/configuration.yml
    - roles/monasca-variables/defaults/main.yml
  tasks:
    - { include: roles/monasca-variables/tasks/service_status.yml, service_name: influxdb, when: database_type=='influxdb'}

- name: cassandra Status
  hosts: FND-CDB
  max_fail_percentage: 0
  become: yes
  tags: [cassandra]
  vars_files:
    - roles/monasca-variables/vars/configuration.yml
    - roles/monasca-variables/defaults/main.yml
  tasks:
    - { include: roles/FND-CDB/tasks/status.yml, service_name: cassandra, when: database_type=='cassandra'}

- name: monasca-api Status
  hosts: MON-API
  max_fail_percentage: 0
  become: yes
  tags: [monasca-api]
  vars_files:
    - roles/monasca-variables/vars/configuration.yml
  tasks:
    - { include: roles/monasca-variables/tasks/service_status.yml, service_name: monasca-api, when: monasca_api_implementation_lang == 'java' }

- name: monasca-persister Status
  hosts: MON-PST
  max_fail_percentage: 0
  become: yes
  tags: [monasca-persister]
  tasks:
    - { include: roles/monasca-variables/tasks/service_status.yml, service_name: monasca-persister}

- name: monasca-notification Status
  hosts: MON-NTF
  max_fail_percentage: 0
  become: yes
  tags: [monasca-notification]
  tasks:
    - { include: roles/monasca-variables/tasks/service_status.yml, service_name: monasca-notification}

- name: storm Status
  hosts: MON-THR
  max_fail_percentage: 0
  become: yes
  tags: [storm, thresh]
  vars_files:
    - roles/storm/defaults/main.yml
    - roles/storm/vars/nodes.yml
  tasks:
    - include: roles/monasca-variables/tasks/service_status.yml service_name=storm-nimbus
    - include: roles/monasca-variables/tasks/service_status.yml service_name=storm-supervisor
    - include: roles/monasca-variables/tasks/service_status.yml service_name=storm-ui
      when: storm_ui_enabled | bool
    - include: roles/monasca-variables/tasks/service_status.yml service_name=storm-logviewer
      when: storm_logviewer_enabled | bool

- name: monasca-thresh Status
  hosts: MON-THR
  max_fail_percentage: 0
  become: yes
  tags: [thresh]
  vars_files:
    - roles/monasca-thresh/vars/nodes.yml
  tasks:
    - include: roles/monasca-variables/tasks/service_status.yml service_name=monasca-thresh
      when: thresh_start_enabled | bool
