#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- include: pbstart.yml
  vars:
    playbook_name: "monasca-agent-deploy.yml"

- name: Install the Monasca Agent on all systems
  hosts: MON-AGN
  become: yes
  tags: [monasca-agent]
  vars_files:
    - roles/monasca-variables/vars/configuration.yml
    - roles/monasca-variables/defaults/main.yml
  roles:
    - {role: monasca-agent,
        monasca_virtualenv_dir: "{{ monasca_agent_virtualenv_dir }}",
        tags: [monasca-agent]}
  tasks:
    - name: Run Monasca Agent detection plugin for the monasca-agent processes
      monasca_agent_plugin:
        name="MonAgent"
        monasca_setup_path="{{monasca_setup_bin_dir}}/monasca-setup"
      register: monasca_agent_detection_result
      until: not monasca_agent_detection_result | failed
      retries: 5
      delay: 5
    - name: Run Monasca Agent detection plugin for ntp
      monasca_agent_plugin:
        name="ntp"
        monasca_setup_path="{{monasca_setup_bin_dir}}/monasca-setup"
      tags: [monasca-agent-ntp]
    - name: Determine if kdump directory exists
      stat: path=/sys/kernel/kexec_crash_loaded
      register: kdump_dir_result
    - name: Determine if kdump is configured
      command: cat /sys/kernel/kexec_crash_loaded
      register: kdump_config_result
      when: kdump_dir_result.stat.exists
    - name: Run Monasca Agent detection plugin for crash detection
      monasca_agent_plugin:
        name="crash"
        monasca_setup_path="{{monasca_setup_bin_dir}}/monasca-setup"
      tags: [monasca-agent-crash]
      when: "kdump_dir_result.stat.exists and '1' in kdump_config_result.stdout"

- name: Install the Monasca Agent libvirt plugin requirements on NOV-CMP (RPM)
  hosts: NOV-CMP:&MON-AGN
  tags: [monasca-agent]
  tasks:
    # these monasca-agent requirements are only on the compute nodes needed
    # that's why they are not in the openstack-monasca-agent package itself
    # Not needed for RHEL computes as monasca-agent is installed in venv
    - name: Install required packages for libvirt plugin (RPM)
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - libvirt-python
        - python-novaclient
        - python-neutronclient
      when:
        - ansible_os_family | lower == 'suse'


- include: pbfinish.yml
  vars:
    playbook_name: "monasca-agent-deploy.yml"
