#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: Configure storm.yaml
  template:
    dest: "{{ storm_conf_file }}"
    owner: "{{ storm_user }}"
    group: "{{ storm_group }}"
    mode: 0644
    src: storm.yaml.j2
  register: ardana_notify_storm_restart_required

- name: Setup Storm supervisor upstart script
  copy: dest={{supervisor_upstart_conf}} owner=root group=root mode=0644 src=storm-supervisor.conf
  when: not use_systemd
  register: ardana_notify_storm_restart_required

- name: Setup Storm supervisor systemd script
  template:
    dest: "{{ supervisor_systemd_service }}"
    owner: root
    group: root
    mode: 0644
    src: storm-supervisor.service.j2
  when: use_systemd
  register: ardana_notify_storm_restart_required

- name: Setup Storm Logviewer upstart script
  copy: dest={{logviewer_upstart_conf}} owner=root group=root mode=0644 src=storm-logviewer.conf
  when: storm_logviewer_enabled and not use_systemd
  register: ardana_notify_storm_restart_required

- name: Setup Storm Logviewer systemd script
  template:
    dest: "{{ logviewer_systemd_service }}"
    owner: root
    group: root
    mode: 0644
    src: storm-logviewer.service.j2
  when: storm_logviewer_enabled and use_systemd
  register: ardana_notify_storm_restart_required

- command: systemctl daemon-reload
  when: use_systemd
