#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- include: ./_set_directories.yml
  vars:
    install_package_result: "{{ ardana_notify_monasca_api_install_result }}"

- name: setup group
  group: name={{monasca_group}} system=yes
  register: ardana_notify_monasca_api_restart_required

- name: Setup user
  user:
    name: "{{ monasca_api_user }}"
    system: yes
    group: "{{ monasca_group }}"
    shell: "{{ monasca_api_shell }}"
  register: ardana_notify_monasca_api_restart_required

- name: monasca-api | configure-pythonimpl | configure api config ini file
  become: yes
  template:
    src: api-config.ini.j2
    dest: "{{ monasca_api_conf_dir }}/api-config.ini"
    owner: "{{ monasca_api_user }}"
    group: "{{ monasca_group }}"
    mode: 0600
  register: ardana_notify_monasca_api_restart_required

- name: monasca-api | configure-pythonimpl | configure api config conf file
  become: yes
  template:
    src: api-config.conf.j2
    dest: "{{ monasca_api_conf_dir }}/api-config.conf"
    owner: "{{ monasca_api_user }}"
    group: "{{ monasca_group }}"
    mode: 0600
  register: ardana_notify_monasca_api_restart_required

- name: monasca-api | configure-pythonimpl | configure api logging conf file
  become: yes
  template:
    src: api-logging.conf.j2
    dest: "{{ monasca_api_conf_dir }}/api-logging.conf"
    owner: "{{ monasca_api_user }}"
    group: "{{ monasca_group }}"
    mode: 0600
  register: ardana_notify_monasca_api_restart_required

#
# create modwsgi file for monasca-api
#

- name: monasca-api | install-pythonimpl | Create /var/www/monasca  directory
  become: yes
  file:
    path: /var/www/monasca
    owner: "{{ monasca_api_user }}"
    group: "{{ monasca_group }}"
    mode: 0755
    state: directory
    recurse: yes

- name: monasca-api | install-pythonimpl | Creating monasca-api global conf directory
  become: yes
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ monasca_api_user }}"
    group: "{{ monasca_group }}"
    mode: "{{ item.permission }}"
    recurse: yes
  with_items:
    - { dir: '{{ monasca_global_conf_dir }}', permission: '0755'}

- name: monasca-api | configure-pythonimpl | configure monasca-api wsgi file
  become: yes
  template:
    src: monasca-api.wsgi.j2
    dest: "{{ monasca_api_bin_dir }}/../lib/python2.7/site-packages/monasca_api/monasca-api.wsgi"
    owner: "{{ monasca_api_user }}"
    group: "{{ monasca_group }}"
    mode: 0755
  register: ardana_notify_monasca_api_apache_restart

- name: monasca-api | configure-pythonimpl | configure monasca-api apache virtualhost
  become: yes
  template:
    src: monasca-api-apache2.conf.j2
    dest: "{{ apache2_vhost_dir }}/monasca-api-apache2.conf"
    mode: 0755
  register: ardana_notify_monasca_api_apache_restart

- name: monasca-api | configure-pythonimpl | configure monasca-api apache virtualhost enabled
  become: yes
  file:
    src: "{{ apache2_vhost_dir }}/monasca-api-apache2.conf"
    dest: /etc/apache2/sites-enabled/monasca-api-apache2.conf
    state: link
  register: ardana_notify_monasca_api_apache_restart
  when: ansible_os_family == 'Debian'

- name: create monasca log dir
  file: path={{monasca_log_dir}} state=directory owner=root group=root mode=0775
  register: ardana_notify_monasca_api_apache_restart

- name: create api log dir
  file: path={{api_log_dir}} state=directory owner=mon-api group=adm mode=0775
  register: ardana_notify_monasca_api_apache_restart

- name: monasca-api | configure-pythonimpl | configure monaca-api apache log file ownership
  become: yes
  file:
    path: "{{ monasca_log_dir }}/api/{{ item }}"
    owner: "{{ monasca_api_user }}"
    group: "{{ monasca_group }}"
    mode: 0640
    state: touch
  with_items:
    - monasca_api_wsgi.log
    - monasca_api_wsgi-access.log

- name: monasca-api | configure-pythonimpl | set monasca-api log file ownership
  file:
    path: "{{ item }}"
    state: touch
    owner: "{{ monasca_api_user }}"
    group: "adm"
    mode: 0640
  with_items:
    - "{{ monasca_log_dir }}/api/monasca_api_wsgi.log"
    - "{{ monasca_log_dir }}/api/monasca_api_wsgi-access.log"

- name: monasca-api | configure-pythonimpl | Create Symlinks for other config files from install
  file:
    src: "{{ monasca_api_conf_dir }}/{{ item }}"
    dest: "{{ monasca_global_conf_dir }}/{{ item }}"
    owner: "{{ monasca_api_user }}"
    group: "{{ monasca_group }}"
    state: link
    mode: 0750
  with_items:
    - api-config.conf
    - api-config.ini
    - api-logging.conf
  become: yes

- name: monasca-api | configure-pythonimpl | Create symbolic link for startup file
  become: yes
  file:
    src: "{{ monasca_api_venv_share_dir }}/../lib/python2.7/site-packages\
          /monasca_api/monasca-api.wsgi"
    dest: "/var/www/monasca/monasca-api"
    owner: root
    group: "{{ monasca_group }}"
    state: link

