#
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: monasca-api| install-pythonimpl | Update venv cache
  become: yes
  install_package:
    cache: update

- name: monasca-api | install-pythonimpl | Installing Monasca API python code
  become: yes
  install_package:
    name: "{%- if deployer_media_legacy_layout|bool -%}
               monasca_api
           {%- else -%}
               monasca
           {%- endif -%}"
    service: monasca-api
    state: present
    activate: act_off
  register: ardana_notify_monasca_api_install_result

- name: monasca-api | install-pythonimpl | Register restart required
  command: echo "monasca api restart required"
  register: ardana_notify_monasca_api_venv_changed_result
  when: ardana_notify_monasca_api_install_result.changed

- name: monasca-api | install-pythonimpl | Register restart required
  command: echo "monasca api restart required"
  notify: ardana_notify_monasca_api_apache_restart
  when: ardana_notify_monasca_api_install_result.changed

- name: monasca-api | install-pythonimpl | Set service conf directories
  set_fact:
    monasca_api_conf_dir: "{{ 'monasca-api' |
      config_dir(ardana_notify_monasca_api_install_result.version) }}"
    monasca_api_venv_dir: "{{ 'monasca-api' |
      venv_dir(ardana_notify_monasca_api_install_result.version) }}"
    monasca_api_bin_dir: "{{ 'monasca-api' |
      bin_dir(ardana_notify_monasca_api_install_result.version) }}"

- name: monasca-api | install-pythonimpl | Install modwsgi dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: monasca_api_dependencies
