#
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
monasca_zookeeper_package_dependencies:
  - openjdk-8-jre-headless
  - default-jre-headless
  - zookeeperd

monasca_zookeeper_restart_packages:
  - default-jre-headless
  - zookeeperd

zookeeper_conf_dir: /etc/zookeeper/conf

# Location of myid file for zookeeper cluster
zookeeper_myid_dir: "{{ zookeeper_conf_dir }}"

zookeeper_java_share_dir: /usr/share/java

# predefined jars defined and available as part of hlinux package
zookeeper_java_share_classpath: "/usr/share/java/jline.jar:/usr/share/java/log4j-1.2.jar:/usr/share/java/xercesImpl.jar:/usr/share/java/xmlParserAPIs.jar:/usr/share/java/netty.jar:/usr/share/java/slf4j-api.jar:/usr/share/java/slf4j-log4j12.jar:/usr/share/java/zookeeper.jar"