#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
influxdb_schema_enabled: true
kafka_topics_enabled: true
mysql_schema_enabled: true
influxdb_admin: "{{ FND_IDB.vars.influxdb_admin_user_name }}"
influxdb_admin_password: "{{ FND_IDB.vars.influxdb_admin_user_password }}"
influxdb_admin_old_password: "{% if FND_IDB.old_vars is defined and FND_IDB.old_vars.influxdb_admin_user_password is defined %}{{ FND_IDB.old_vars.influxdb_admin_user_password }}{% else %}{{ influxdb_admin_password }}{% endif %}"
influxdb_dbname: mon
influxdb_retention_policy: "90d"
influxdb_shard_duration: "7d"
influxdb_script_dir: /root
mysql_admin: root
monasca_mysql_db: "{{ MON_API.consumes_FND_MDB.vars.databases.monasca.dbname }}"
# enable cassandra schema
cassandra_conf_dir: "{{ '/etc/cassandra/conf' if ansible_os_family == 'Suse' else '/etc/cassandra' }}"
cassandra_schema_enabled: true
cassandra_hosts: "{{ FND_CDB.members.inter_node_cluster }}"

cassandra_local_hostname: >
  {{ (cassandra_hosts |
      selectattr('ardana_ansible_host','equalto', inventory_hostname) |
      first).host }}

cassandra_contact_points: "{% if database_type == 'cassandra' %}{{ MON_PST.consumes_FND_CDB.members.client }}{% endif %}"
cassandra_port: "{% if database_type == 'cassandra' %}{{ MON_PST.consumes_FND_CDB.members.client[0].port }}{% endif %}"
cassandra_user: "{% if database_type == 'cassandra' %}{{ MON_PST.consumes_FND_CDB.vars.cassandra_monasca_persister_user }}{% endif %}"
cassandra_password: "{% if database_type == 'cassandra' %}{{ MON_PST.consumes_FND_CDB.vars.cassandra_monasca_persister_password }}{% endif %}"
cassandra_datacenter_identifier: "{% if database_type == 'cassandra' %}{{ MON_PST.consumes_FND_CDB.vars.cassandra_datacenter_identifier }}{% endif %}"
cassandra_replication_factor: >
  {% if database_type == 'cassandra' %}{{ [MON_PST.consumes_FND_CDB.vars.cassandra_max_replication_factor, cassandra_node_count | int] | min }}{% endif %}
cassandra_client_connect_timeout: 120
cassandra_client_request_timeout: 120
cassandra_admin_user: "{% if database_type == 'cassandra' %}{{ FND_CDB.vars.cassandra_admin_user }}{% endif %}"
cassandra_admin_password: "{% if database_type == 'cassandra' %}{{ FND_CDB.vars.cassandra_admin_password }}{% endif %}"

mysql_root_dir: /var/lib/mysql
mysql_schema_dir: /root
monasca_schema_version: 4
monasca_schema_file: "{{ mysql_schema_dir }}/mon.sql"
monasca_script_file: "{{ mysql_schema_dir }}/mysql_schema.py"
monasca_mysql_schema_sync_script_file: "{{ mysql_schema_dir }}/mysql_schema_sync.py"

kafka_events_partitions: 12
kafka_metrics_partitions: 64
# This should be the number of systems running the Notification Engine
kafka_retry_periodic_notifications_partitions: 3
kafka_node_count: "{{ FND_KFK.members.private | length }}"
kafka_replicas: "{% if kafka_node_count | int > 3 %}3{% else %}{{ kafka_node_count }}{% endif %}"
kafka_segment_minutes: 15

kafka_topics:
  metrics: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_metrics_partitions }}" }
  events: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  raw-events: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  transformed-events: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  stream-definitions: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  transform-definitions: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  alarm-state-transitions: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  alarm-notifications: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  stream-notifications: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  retry-notifications: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_retry_periodic_notifications_partitions }}" }
  60-seconds-notifications: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_retry_periodic_notifications_partitions }}" }


zookeeper_nodes: "{{ FND_KFK.consumes_FND_ZOO.members.private }}"
zookeeper_hosts: "{% for node in zookeeper_nodes %}{{ node.host }}:{{ node.port }}{% if not loop.last %},{% endif %}{% endfor %}"

influxdb_node_count: "{{ FND_IDB.members.private | length }}"
influxdb_replication_factor: "{% if influxdb_node_count | int > 3 %}3{% else %}{{ influxdb_node_count }}{% endif %}"
influxdb_url: "{% if database_type == 'influxdb' %}{{ MON_API.consumes_FND_IDB.vips.private[0].url }}{% endif %}"
mon_influxdb_users:
  - username: "{{ MON_API.consumes_FND_IDB.vars.influxdb_monasca_api_user }}"
    password: "{{ MON_API.consumes_FND_IDB.vars.influxdb_monasca_api_password | quote }}"
  - username: "{{ MON_PST.consumes_FND_IDB.vars.influxdb_monasca_persister_user }}"
    password: "{{ MON_PST.consumes_FND_IDB.vars.influxdb_monasca_persister_password | quote }}"

rebuild: False

monasca_api_mysql_user: "{{ MON.consumes_FND_MDB.vars.accounts.monasca_api.username }}"
monasca_api_mysql_password: "{{ MON.consumes_FND_MDB.vars.accounts.monasca_api.password | quote }}"
mysql_host: "{{ MON_API.consumes_FND_MDB.vips.private[0].host }}"

monasca_schema_system_cacert_file: "{{ trusted_ca_bundle }}"
