#
#  (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: monasca-schema | cassandra | Copy over cassandra schema cql file
  template:
    src: mon_cassandra_schema.cql.j2
    dest: "{{ cassandra_conf_dir }}/mon_cassandra_schema.cql"
    mode: 0660
  register: cql_schema_status

- name: monasca-schema | cassandra | Write schema to cassandra
  become: yes
  shell: >
    /usr/bin/cqlsh -u {{ cassandra_admin_user }}
    -p {{ cassandra_admin_password }}
    -f {{ cassandra_conf_dir }}/mon_cassandra_schema.cql
    --connect-timeout {{ cassandra_client_connect_timeout }}
    --request-timeout {{ cassandra_client_request_timeout }}
    {{ cassandra_local_hostname }}
  no_log: True
  when: cql_schema_status | changed
  run_once: True
  ignore_errors: True
  register: schema_result

- name: monasca-schema | clear schema if failed
  become: yes
  file:
    path: "{{ cassandra_conf_dir }}/mon_cassandra_schema.cql"
    state: absent
  when: schema_result is defined and schema_result.rc != 0

- name: monasca-schema | check schema fail
  fail:
    msg: failed to create monasca schema
  when: schema_result is defined and schema_result.rc != 0